function mytweets(){var L='',lb='" for "gwt:onLoadErrorFn"',jb='" for "gwt:onPropertyErrorFn"',W='"><\/script>',Y='#',Jb='.cache.html',$='/',Db='266C7B1709303C789A57C465783EA338',Eb='2D67B7D93B8EC6418427CC9A14B7953C',Fb='5E50A5F7F7548BCA103078C7E191D97E',Gb='9058FC9DDF48E22AD06906AFBC46C2CE',Rb='<script defer="defer">mytweets.onInjectionDone(\'mytweets\')<\/script>',V='<script id="',gb='=',Z='?',ib='Bad handler "',Hb='D0DCB779A7796A6FA16705949B45C242',Ib='DC8A2F917BCF5CEE2DDC2F414A499A28',Qb='DOMContentLoaded',X='SCRIPT',U='__gwt_marker_mytweets',_='base',P='begin',O='bootstrap',bb='clear.cache.gif',fb='content',T='end',xb='gecko',yb='gecko1_8',Q='gwt.hosted=',R='gwt.hybrid',Kb='gwt/standard/standard.css',kb='gwt:onLoadErrorFn',hb='gwt:onPropertyErrorFn',eb='gwt:property',Pb='head',Bb='hosted.html?mytweets',Ob='href',wb='ie6',vb='ie8',mb='iframe',ab='img',nb="javascript:''",Lb='link',Ab='loadExternalRefs',cb='meta',pb='moduleRequested',S='moduleStartup',ub='msie',M='mytweets',db='name',rb='opera',ob='position:absolute;width:0;height:0;border:none',Mb='rel',tb='safari',Cb='selectingPermutation',N='startup',Nb='stylesheet',zb='unknown',qb='user.agent',sb='webkit';var k=window,l=document,m=k.__gwtStatsEvent?function(a){return k.__gwtStatsEvent(a)}:null,n,o,p,q=L,r={},s=[],t=[],u=[],v,w;m&&m({moduleName:M,subSystem:N,evtGroup:O,millis:(new Date).getTime(),type:P});if(!k.__gwt_stylesLoaded){k.__gwt_stylesLoaded={}}if(!k.__gwt_scriptsLoaded){k.__gwt_scriptsLoaded={}}function x(){var b=false;try{var c=k.location.search;return (c.indexOf(Q)!=-1||k.external&&k.external.gwtOnLoad)&&c.indexOf(R)==-1}catch(a){}x=function(){return b};return b}
function y(){if(n&&o){var b=l.getElementById(M);var c=b.contentWindow;if(x()){c.__gwt_getProperty=function(a){return E(a)}}mytweets=null;c.gwtOnLoad(v,M,q);m&&m({moduleName:M,subSystem:N,evtGroup:S,millis:(new Date).getTime(),type:T})}}
function z(){var e,f=U,g;l.write(V+f+W);g=l.getElementById(f);e=g&&g.previousSibling;while(e&&e.tagName!=X){e=e.previousSibling}function h(a){var b=a.lastIndexOf(Y);if(b==-1){b=a.length}var c=a.indexOf(Z);if(c==-1){c=a.length}var d=a.lastIndexOf($,Math.min(c,b));return d>=0?a.substring(0,d+1):L}
;if(e&&e.src){q=h(e.src)}if(q==L){var i=l.getElementsByTagName(_);if(i.length>0){q=i[i.length-1].href}else{q=h(l.location.href)}}else if(q.match(/^\w+:\/\//)){}else{var j=l.createElement(ab);j.src=q+bb;q=h(j.src)}if(g){g.parentNode.removeChild(g)}}
function A(){var b=document.getElementsByTagName(cb);for(var c=0,d=b.length;c<d;++c){var e=b[c],f=e.getAttribute(db),g;if(f){if(f==eb){g=e.getAttribute(fb);if(g){var h,i=g.indexOf(gb);if(i>=0){f=g.substring(0,i);h=g.substring(i+1)}else{f=g;h=L}r[f]=h}}else if(f==hb){g=e.getAttribute(fb);if(g){try{w=eval(g)}catch(a){alert(ib+g+jb)}}}else if(f==kb){g=e.getAttribute(fb);if(g){try{v=eval(g)}catch(a){alert(ib+g+lb)}}}}}}
function D(a,b){var c=u;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
function E(a){var b=t[a](),c=s[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(w){w(a,d,b)}throw null}
var F;function G(){if(!F){F=true;var a=l.createElement(mb);a.src=nb;a.id=M;a.style.cssText=ob;a.tabIndex=-1;l.body.appendChild(a);m&&m({moduleName:M,subSystem:N,evtGroup:S,millis:(new Date).getTime(),type:pb});a.contentWindow.location.replace(q+I)}}
t[qb]=function(){var b=navigator.userAgent.toLowerCase();var c=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(b.indexOf(rb)!=-1){return rb}else if(b.indexOf(sb)!=-1){return tb}else if(b.indexOf(ub)!=-1){if(document.documentMode>=8){return vb}else{var d=/msie ([0-9]+)\.([0-9]+)/.exec(b);if(d&&d.length==3){var e=c(d);if(e>=6000){return wb}}}}else if(b.indexOf(xb)!=-1){var d=/rv:([0-9]+)\.([0-9]+)/.exec(b);if(d&&d.length==3){if(c(d)>=1008)return yb}return xb}return zb};s[qb]={gecko:0,gecko1_8:1,ie6:2,ie8:3,opera:4,safari:5};mytweets.onScriptLoad=function(){if(F){o=true;y()}};mytweets.onInjectionDone=function(){n=true;m&&m({moduleName:M,subSystem:N,evtGroup:Ab,millis:(new Date).getTime(),type:T});y()};z();var H;var I;if(x()){if(k.external&&(k.external.initModule&&k.external.initModule(M))){k.location.reload();return}I=Bb;H=L}A();m&&m({moduleName:M,subSystem:N,evtGroup:O,millis:(new Date).getTime(),type:Cb});if(!x()){try{D([xb],Db);D([vb],Eb);D([wb],Fb);D([tb],Gb);D([yb],Hb);D([rb],Ib);H=u[E(qb)];I=H+Jb}catch(a){return}}var J;function K(){if(!p){p=true;if(!__gwt_stylesLoaded[Kb]){var a=l.createElement(Lb);__gwt_stylesLoaded[Kb]=a;a.setAttribute(Mb,Nb);a.setAttribute(Ob,q+Kb);l.getElementsByTagName(Pb)[0].appendChild(a)}y();if(l.removeEventListener){l.removeEventListener(Qb,K,false)}if(J){clearInterval(J)}}}
if(l.addEventListener){l.addEventListener(Qb,function(){G();K()},false)}var J=setInterval(function(){if(/loaded|complete/.test(l.readyState)){G();K()}},50);m&&m({moduleName:M,subSystem:N,evtGroup:O,millis:(new Date).getTime(),type:T});m&&m({moduleName:M,subSystem:N,evtGroup:Ab,millis:(new Date).getTime(),type:P});l.write(Rb)}
mytweets();